services:
  website:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3000:3000"
  
  nginx:
    build:
     context: /nginx
     dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - website